version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: increase
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.12.1
    - 1.9.1
  - dependency-name: codecov
    versions:
    - 0.5.1
  - dependency-name: rails
    versions:
    - 6.0.3.2
    - 6.0.3.5
    - 6.1.3
  - dependency-name: regexp_parser
    versions:
    - 2.1.0
  - dependency-name: faker
    versions:
    - 2.13.0
    - 2.16.0
  - dependency-name: mini_magick
    versions:
    - 4.11.0
  - dependency-name: ruby-progressbar
    versions:
    - 1.11.0
  - dependency-name: figaro
    versions:
    - 1.2.0
  - dependency-name: rails-erd
    versions:
    - 1.6.0
    - 1.6.1
  - dependency-name: gemsurance
    versions:
    - 0.10.0
  - dependency-name: carrierwave
    versions:
    - 2.1.0
    - 2.1.1
  - dependency-name: rubyzip
    versions:
    - 1.3.0
  - dependency-name: nokogiri
    versions:
    - 1.10.8
    - 1.11.0
  - dependency-name: json
    versions:
    - 2.3.1
    - 2.5.1
  - dependency-name: rack
    versions:
    - 2.2.3
  - dependency-name: simplecov
    versions:
    - 0.19.0
  - dependency-name: loofah
    versions:
    - 2.6.0
  - dependency-name: websocket-extensions
    versions:
    - 0.1.5
  - dependency-name: kaminari
    versions:
    - 1.2.1
  - dependency-name: puma
    versions:
    - 4.3.5
  - dependency-name: minitest
    versions:
    - 5.14.1
  - dependency-name: brakeman
    versions:
    - 4.7.1
