#!/bin/bash
set -e

echo '----------------------'
echo 'BEGIN: bundle outdated'
echo '----------------------'
docker/run bundle outdated
echo '--------------------'
echo 'END: bundle outdated'
echo '--------------------'
