#!/bin/bash

# Run this script before entering "git add" and "git commit".

docker/test

docker/brakeman

docker/cop

docker/rbp

echo '----------'
echo 'git status'
git status

docker/outline_short

echo '----------'
echo 'git status'
git status
