#!/bin/bash

DB_ROOT=$1
DB_USERNAME=$2
DB_PASSWORD=$3

echo 'Configure config/database.yml'
cp config/database.yml.docker config/database.yml

echo 'Configure .env-docker/development/database'
cp .env-docker/development/database-template .env-docker/development/database
docker/replace_sif 'POSTGRES_DB_1' $DB_ROOT '.env-docker/development/database'
docker/replace_sif 'POSTGRES_USER_1' $DB_USERNAME '.env-docker/development/database'
docker/replace_sif 'POSTGRES_PASSWORD_1' $DB_PASSWORD '.env-docker/development/database'

echo 'Configure init.sql'
cp init.sql.template init.sql
docker/replace_sif 'POSTGRES_USER_1' $DB_USERNAME 'init.sql'
docker/replace_sif 'POSTGRES_PASSWORD_1' $DB_PASSWORD 'init.sql'
chmod +x init.sql
