name: Lint

on: [push]

jobs:
  verify:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependent libraries
        run: sudo apt-get install -y libpq-dev
      - name: Set up Ruby and run bundle install
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
          bundler-cache: true
      - name: Show Ruby version
        run: ruby -v
      - name: RuboCop
        run: bundle exec rubocop -D
      - name: Rails Best Practices
        run: bundle exec rails_best_practices .
